version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  migration:
    depends_on:
      - db
    image: migrate/migrate
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - "./scripts/wait-for-db.sh:/wait-for-db.sh"
      - "./migrations/:/migrations/"
    entrypoint: /wait-for-db.sh db:5432 --timeout=10 -- /migrate -verbose -path=/migrations/ -database postgres://postgres:example@db/postgres?sslmode=disable up
  app:
    depends_on:
      - db
      - migration
    image: golang:1.12.2
    environment:
      GO111MODULE: "on"
      PORT: ":50051"
      DATABASE_ADDR: postgres://postgres:example@db/postgres?sslmode=disable
    volumes:
      - "./:/app/"
    entrypoint: /app/scripts/run.sh
    ports:
      - "50051:50051"
  integration_tests:
    image: golang:1.12.2
    environment:
      GO111MODULE: "on"
      DATABASE_ADDR: postgres://postgres:example@db/postgres?sslmode=disable
      APP_ADDR: "app:50051"
    volumes:
      - "./:/app/"
    command: go test -count=1 ./integration_tests
    working_dir: /app/