version: "3"
services:
  db:
    image: cockroachdb/cockroach:v2.1.6
    command: start --insecure
  migration:
    depends_on:
      - db
    image: migrate/migrate
    volumes:
      - "./scripts/wait-for-db.sh:/wait-for-db.sh"
      - "./migrations/:/migrations/"
    entrypoint:
     - /wait-for-db.sh
     - db
     - "./migrate -path=/migrations/ -database cockroachdb://root@db:26257?sslmode=disable up"
  app:
    depends_on:
      - db
      - migration
    image: golang:1.12.2
    environment:
      GO111MODULE: "on"
      PORT: ":50051"
      DATABASE_ADDR: postgresql://root@db:26257?sslmode=disable
    volumes:
      - "./:/app/"
    command: /app/scripts/wait-for-db.sh db /app/scripts/run.sh
    ports:
      - "50051:50051"
  integration_tests:
    image: golang:1.12.2
    environment:
      GO111MODULE: "on"
      DATABASE_ADDR: postgresql://root@db:26257?sslmode=disable
      APP_ADDR: "app:50051"
    volumes:
      - "./:/app/"
    command: go test -count=1 ./integration_tests
    working_dir: /app/